refactor(ci): melhorias nos jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,11 @@
 name: Build Microservices
 
-on: workflow_call
+on:
+  workflow_call:
+    inputs:
+      spring_profile:
+        type: string
+        required: true
 
 jobs:
   build:
@@ -10,6 +15,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Validate environment variables
+        run: |
+          if [ -z "${{ inputs.spring_profile }}" ]; then
+            echo "SPRING_PROFILES_ACTIVE is not set!"
+            exit 1
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
         with:
@@ -17,12 +29,17 @@ jobs:
 
       - name: Set up Docker Compose
         run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose --version
 
       - name: Login to Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          if [ $? -ne 0 ]; then
+            echo "Docker Hub login failed!"
+            exit 1
+          fi
 
       - name: Build Docker images
         run: |
